name: Check

on:
  pull_request:
    paths:
      - 'lib/**'
      - 'test/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: subosito/flutter-action@v2

      - name: Test
        run: flutter test
