name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: dart-lang/setup-dart@v1

      - name: Install
        run: flutter pub get

      - name: Publish
        run: flutter pub publish --force