name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
      - name: Install
        run: dart pub get

      - name: Publish
        run: dart pub publish --force